# SPDX-License-Identifier: CC0-1.0
# SPDX-FileCopyrightText: 2022 Linaro Ltd.
# SPDX-FileCopyrightTest: 2022 Viresh Kumar <viresh.kumar@linaro.org>

[workspace]

members = [
    "gpiosim-sys",
    "libgpiod",
    "libgpiod-sys"
]
