# SPDX-License-Identifier: CC0-1.0
# SPDX-FileCopyrightText: 2022 Linaro Ltd.
# SPDX-FileCopyrightText: 2022 Viresh Kumar <viresh.kumar@linaro.org>

[package]
name = "gpiosim-sys"
version = "0.1.0"
authors = ["Viresh Kumar <viresh.kumar@linaro.org>"]
description = "gpiosim header bindings"
repository = "https://git.kernel.org/pub/scm/libs/libgpiod/libgpiod.git"
categories = ["external-ffi-bindings", "os::linux-apis"]
rust-version = "1.60"
keywords = ["libgpiod", "gpio", "gpiosim"]
license = "Apache-2.0 OR BSD-3-Clause"
edition = "2021"

[dependencies]
errno = "0.2.8"
libgpiod = { path = "../libgpiod" }

[build-dependencies]
bindgen = "0.63"
cc = "1.0.46"
